# Default values for your Helm chart
replicaCount: 1
image:
  repository: hdf-docker-registry/cmon-mobile/service-manipulator
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: nexus-docker-secret

# MongoDb configuration
mongodb:
  ip: 10.0.72.224
  port: 27017
  database: Cmon_Mobile

# Kafka configuration
kafka:
  ip: 10.0.73.91
  port: 9092
  # Add other Kafka configurations if needed

nexus:
  secret: nexus-secret

# Service configuration
service:
  name: manipulator-service-chart
  type: LoadBalancer
  port: 8083
  # Add other service configurations if needed

readinessProbe:
  httpGet:
    path: /ready
    port: 8083
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /healthz
    port: 8083
  initialDelaySeconds: 30
  periodSeconds: 10

# Pod annotations
podAnnotations: {}